#include "algorithms/bitap.h"
#include "algorithms/levinshtein.h"
#include "algorithms/simple_match.h"
#include "algorithms/jaro_winkler.h"
#include "algorithms/wagner_fisher.h"
#include "algorithms/trigram_match.h"