#EXTENSION = fuzzy
#MODULE_big = fuzzy
#DATA = fuzzy--1.0.sql
#OBJS = fuzzy.o
#
#PG_CONFIG = pg_config
#PGXS := $(shell $(PG_CONFIG) --pgxs)
#include $(PGXS)


EXTENSION = fuzzy
MODULE_big = fuzzy
DATA = fuzzy--1.0.sql
OBJS = fuzzy.o

PG_CONFIG = pg_config
PGXS := $(shell $(PG_CONFIG) --pgxs)
include $(PGXS)